"""Added numero_residencia and data_nascimento and genero and numer_convenio fields to Paciente

Revision ID: b6b17a9640d2
Revises: 97748adde3e9
Create Date: 2024-07-24 16:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b17a9640d2'
down_revision = '97748adde3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_residencia', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('genero', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('convenio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('numero_convenio', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_paciente_consulta', 'consulta', ['id'], ['paciente_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_constraint('fk_paciente_consulta', type_='foreignkey')
        batch_op.drop_column('numero_convenio')
        batch_op.drop_column('convenio')
        batch_op.drop_column('genero')
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('numero_residencia')

    # ### end Alembic commands ###
